// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvosmAYKO7KqqK7TmfqOp80enWxABCmo',
    appId: '1:1048603734662:web:fdf1bee612ce354ee31707',
    messagingSenderId: '1048603734662',
    projectId: 'rrqproject-cce84',
    authDomain: 'rrqproject-cce84.firebaseapp.com',
    storageBucket: 'rrqproject-cce84.appspot.com',
    measurementId: 'G-PF1S3WQNNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3z_krkeyO846TCuu_04mhwWkpAjQwrA4',
    appId: '1:1048603734662:android:255a2952a4788191e31707',
    messagingSenderId: '1048603734662',
    projectId: 'rrqproject-cce84',
    storageBucket: 'rrqproject-cce84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEMetbMojXWv-ApzQNp5lHDI23PoHiPY',
    appId: '1:1048603734662:ios:5fffedbac693d08ce31707',
    messagingSenderId: '1048603734662',
    projectId: 'rrqproject-cce84',
    storageBucket: 'rrqproject-cce84.appspot.com',
    iosClientId: '1048603734662-diol5v62b8kgfenb7hh3nhlim0v07s5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.rrqNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEMetbMojXWv-ApzQNp5lHDI23PoHiPY',
    appId: '1:1048603734662:ios:5fffedbac693d08ce31707',
    messagingSenderId: '1048603734662',
    projectId: 'rrqproject-cce84',
    storageBucket: 'rrqproject-cce84.appspot.com',
    iosClientId: '1048603734662-diol5v62b8kgfenb7hh3nhlim0v07s5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.rrqNews',
  );
}
